# Use this file to control the main attributes of the website

# You
name: Chan Ming Hao

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Resume for Chan Ming Hao

# SEO description
description: Digital resume for Chan Ming Hao, Full Stack Web Developer

# URL of this resume
url: 'https://cmh114933.github.io'

# URL of your personal website (make same as URL if you don't have one)
personal: 'https://github.com/cmh114933'

# these should be pretty self-explanatory :-P
email: cmh114933@gmail.com

# Show this in the footer
copyright: All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
# analytics: 

gems: [jekyll-assets]

# Jekyll assets gem
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Files in this repo that we don't want to go to the web
exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]
